name: Build and Upload APK3

on:
  workflow_dispatch:
  push:
    branches:
      - dependabot/gradle/com.github.hyperdevs-team-poeditor-android-gradle-plugin-3.4.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up JDK 16
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Git Hooks
        run: ./gradlew installGitHooks

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        run: |
          curl -H "Max-Downloads: 1" -H "Max-Days: 5" --upload-file ./app/build/outputs/apk/debug/app-debug.apk https://transfer.sh/dirtydiaperpuppy.apk

